### ISSUE TITLE
Transformation error! Response status: 500

### ISSUE THREAD

**Issue by muzzamilr** [Jonarzz/figma-tokens-transformer#1]
I tried the figma-tokens-transformer for Ant Design version 5 using the example app provided.
I updated the antd version, figma-tokens-transformer version. I created the secret and config json file manually and ran the transform command.
I am using the license key of Ant Design Figma UI Kit. which is in form of xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
I am using Ubuntu 22.04 x86_64
I was returning 500 error, I don't know why.
![Screenshot from 2023-01-26 21-40-48](https://user-images.githubusercontent.com/62418589/214897243-8db1debd-ca08-4d8f-8300-7832e93a0f6a.png)
![Screenshot from 2023-01-26 21-43-09](https://user-images.githubusercontent.com/62418589/214897342-aa18c9b9-5996-4fc2-9bf0-53f78342d571.png)
![Screenshot from 2023-01-26 21-43-16](https://user-images.githubusercontent.com/62418589/214897407-b9f979af-dfac-4c3d-932a-bfcd109eba15.png)

Kindly look into it and please share a sample output file for ant-tokens and create an example app for antd v5 using config provider

**Comment by MusabAkram** [comment]
Facing same issue, when running the transform command on antD v5. getting following `error`
``Transformation error! TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined``

**Comment by muzzamilr** [comment]
Can you also specify, what format of tokens file will it accept because for some tokens.json files it is working fine but for some it returns internal server error

**Comment by Jonarzz** [comment]
Hello, thanks for reaching out. Is the problem still occurring? If so, please contact [hi@antforfigma.com](mailto:hi@antforfigma.com) with all the details and we'll look into it. Thank you and sorry for the inconvenience.

**Comment by kboikovFormind** [comment]
@Jonarzz Hello, i tried to reach you throw that [email](mailto:hi@antforfigma.com), but without any success, could you help me with the same issue? 

It seems, like if i'll provide empty json file, it works fine, but when i tried to use token.json, generated by Token Studio, it responds me with 500

Also, the tool worked fine a month ago, and for a week now it returns a 500 error

**Comment by Jonarzz** [comment]
@kboikovFormind, hello, and please acceptmy apologies. 

We'll reach out back to you using the mail, but in the meantime could you tell me if you've tried with a `tokens.json` file created by Token Studio without making any changes to it? Please, try that and if that works, then it would mean some problems with the changes made in the tokens - to properly analyze that we'd need your JSON file after the changes. If that's possible, please send the file to the hi@antforfigma.com email.

Are you using Ant Design v4 or v5 and do you have `tokens-figma-transformer` configured appropriately?

**Comment by kboikovFormind** [comment]
@Jonarzz Yep, i used `tokens.json` without any changes, i tried it one more time 5 mins ago, and its still the same result.
I've already sent mail to [hi@antforfigma.com](mailto:hi@antforfigma.com) and it also includes screenshot of respond from server, and `tokens.json` file
I'm using v5, and yes, everything related to configuration is okay, at least, it wasn't changed since it works before.

**Comment by Jonarzz** [comment]
@kboikovFormind, please try again now - there was a problem on the backend side and it should be fixed.

**Comment by kboikovFormind** [comment]
@Jonarzz thanks, now it works for my previous `tokens.json`, but i just generated a new one, with new styles, and it broke.

i've provided a new file with a new mail to the same email.

**Comment by Jonarzz** [comment]
@kboikovFormind 
There is no "light" group in the tokens and this group is used as the base for other token groups. If another group does not contain a certain token, but "light" contains it, the value from "light" group is used.

Please, find the answer to the last question in the FAQ section here: https://matt-wierzbicki.notion.site/matt-wierzbicki/Figma-Tokens-Sync-for-Ant-Design-System-for-Figma-36bc6e2ace0c441ca17a5da42e74d257
